### ISSUE TITLE
Enhancement: Add future posts

### ISSUE THREAD

**Issue by Stevie-Ray** [mageplaza/magento-2-blog-extension#10]
I've created a way to allow my client to create "future posts"

By adding the following code to `Blog/Adminhtml/Post/Edit/Tab/Post.php`

```
$fieldset->addField(
            'created_at',
            'date',
            [
                'name'  => 'created_at',
                'label' => __('Date'),
                'title' => __('Date'),
                'date_format' => 'yyyy-MM-dd',
            ]
        );

```
And editing the template in `view/frontend/templates/post/index.phtml` to check if the post is before the current date.

Would be nice to see this in a future update!

**Comment by imsamthomas** [comment]
Thanks for your suggestion.
We have fixed in commit https://github.com/mageplaza/magento-2-blog-extension/pull/13/commits/cd99157dd986c1732773b530d015e052a13654d5
