### ISSUE TITLE
Javascript error: Uncaught ReferenceError: Unable to process binding "css: function (){return stickyClass }"

### ISSUE THREAD

**Issue by rhertogh** [mageplaza/magento-2-blog-extension#6]
Environment:
Magento 2.1.0, PHP 5.6.24

Bug:
When viewing the posts in the admin interface, the following JS error occurs:

`Uncaught ReferenceError: Unable to process binding "css: function (){return stickyClass }"
Message: stickyClass is not definedcss @ VM17101:3update @ knockout.js:3803ko.dependentObservable.disposeWhenNodeIsRemoved @ knockout.js:3004evaluateImmediate @ knockout.js:1737ko.computed.ko.dependentObservable @ knockout.js:1946(anonymous function) @ knockout.js:3002arrayForEach @ knockout.js:151applyBindingsToNodeInternal @ knockout.js:2974applyBindingsToNodeAndDescendantsInternal @ knockout.js:2854ko.applyBindings @ knockout.js:3065_super @ wrapper.js:73applyBindings @ bound-nodes.js:116(anonymous function) @ wrapper.js:78(anonymous function) @ knockout.js:4862invokeForEachNodeInContinuousRange @ knockout.js:4813activateBindingsOnContinuousNodeArray @ knockout.js:4860executeTemplate @ knockout.js:4908ko.dependentObservable.disposeWhen @ knockout.js:4950evaluateImmediate @ knockout.js:1737evaluatePossiblyAsync @ knockout.js:1677notifySubscribers @ knockout.js:1103observable.valueHasMutated @ knockout.js:1300observable @ knockout.js:1285(anonymous function) @ engine.js:54fire @ jquery.js:3099fireWith @ jquery.js:3211(anonymous function) @ jquery.js:3263fire @ jquery.js:3099fireWith @ jquery.js:3211deferred.(anonymous function) @ jquery.js:3301(anonymous function) @ loader.js:96execCb @ require.js:1650context.execCb @ resolver.js:131check @ require.js:866(anonymous function) @ require.js:1113(anonymous function) @ require.js:132(anonymous function) @ require.js:1156each @ require.js:57emit @ require.js:1155check @ require.js:917enable @ require.js:1143init @ require.js:774(anonymous function) @ require.js:991(anonymous function) @ require.js:132(anonymous function) @ text.js:149xhr.onload @ text.js:112`

**Comment by imsamthomas** [comment]
Please try to run deploy static content first.
``php bin/magento setup:static-content:deploy``

**Comment by imsamthomas** [comment]
hi @rhertogh,
Are you still getting same issue?

**Comment by blizam** [comment]
I'm having the same issue... chache and static content have both been manually flushed and redeployed... on the latest 2.1.0 blog version running Mage 2.1.5

**Comment by jghaanstra** [comment]
Has anyone figured out a solution for this issue?
